- platform: template
  sensors:
    vacuum_status:
      friendly_name: Vacuum - Status
      value_template: 'Status: {{ states.vacuum.zosia.attributes.status }}'
      icon_template: >
       {% set val =  states.vacuum.zosia.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Vacuum - Fan Speed
      value_template: '{{ states.vacuum.zosia.attributes.fan_speed }}'
      icon_template: 'mdi:speedometer'
    vacuum_battery:
      friendly_name: Vacuum - Battery
      value_template: 'Bateria: {{ states.vacuum.zosia.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: '{{ states.vacuum.zosia.attributes.battery_icon }}'
    vacuum_cleaning_time:
      friendly_name: Vacuum - Time of Last Cycle
      value_template: '{{ states.vacuum.zosia.attributes.s_time }}'
      icon_template: 'mdi:timer'
    vacuum_cleaned_area:
      friendly_name: Vacuum - Area of Last Cycle
      unit_of_measurement: 'm ²'
      value_template: '{{ states.vacuum.zosia.attributes.s_area }}'
      icon_template: 'mdi:ruler'
    vacuum_cleanmainbrush:
      friendly_name: Vacuum - Main brush hours
      # unit_of_measurement: '%'
      value_template: 'Główna szczotka: {{states.vacuum.zosia.attributes.main_brush_hours}}h | {{(states.vacuum.zosia.attributes.main_brush_hours / 360 * 100) | round(0) }}%'
      icon_template: 'mdi:screwdriver'
    vacuum_cleansidebrush:
      friendly_name: Vacuum - Side brush hours
      # unit_of_measurement: '%'
      value_template: 'Boczna szczotka: {{states.vacuum.zosia.attributes.side_brush_hours}}h | {{(states.vacuum.zosia.attributes.side_brush_hours / 180 * 100) | round(0) }}%'
      icon_template: 'mdi:screwdriver'
    vacuum_mop:
      friendly_name: Vacuum - Is mop installed
      value_template: >-
        {% if states.vacuum.zosia.attributes.mop_type == 1 %}
          Gotowy
        {% else %}
          Brak
        {% endif %}
      icon_template: 'mdi:screwdriver'
    vacuum_dustbox:
      friendly_name: Vacuum - Dustbox type
      value_template: >-
        {% if states.vacuum.zosia.attributes.box_type == 1  %}
          Na kurz
        {% elif states.vacuum.zosia.attributes.box_type == 2  %}
          Z wodą
        {% elif states.vacuum.zosia.attributes.box_type == 3  %}
          Na kurz z wodą
        {% else %}
          Brak
        {% endif %}
      icon_template: 'mdi:screwdriver'
    vacuum_cleanmode:
      friendly_name: Vacuum - Cleaning Mode
      value_template: >-
        {% if states.vacuum.zosia.attributes.is_mop == 0  %}
          Odkurzanie
        {% elif states.vacuum.zosia.attributes.is_mop == 1  %}
          Odkurzanie & Mop
        {% elif states.vacuum.zosia.attributes.is_mop == 2  %}
        Mop
        {% else %}
          Nie gotowy
        {% endif %}
      icon_template: 'mdi:screwdriver'
    vacuum_watergrade:
      friendly_name: Vacuum - Water level
      value_template: >-
        {% if states.vacuum.zosia.attributes.water_grade == 11  %}
          Ilość wody: Mała
        {% elif states.vacuum.zosia.attributes.water_grade == 12  %}
          Ilość wody: Średnia
        {% elif states.vacuum.zosia.attributes.water_grade == 13  %}
          Ilość wody: Duża
        {% else %}
          Ilość wody: brak
        {% endif %}